alerta:
  image: alerta/alerta-web:latest
  ports:
    - 80:80/tcp
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
  environment:
    MONGO_REPLSET: ${replset_name}
  external_links:
    - ${mongo_link}:mongo
