.catalog:
  name: Alerta
  version: 1.0.0
  description: |
    Alert manager.
  questions:
    - variable: "mongo_link"
      description: stack/service link or external service link to mongo.
      label: "Mongo stack/service"
      default: "MongoDB/mongo-cluster"
      required: true
      type: "service"
    - variable: replset_name
      description: "Name of the MongoDB replicaSet"
      label: "ReplicaSet Name"
      type: "string"
      required: true
      default: "rs0"
alerta:
  scale: 1