.catalog:
  name: "Prometheus"
  version: "1.0.2"
  description: "Prometheus Monitoring Solution"
  minimum_rancher_version: v0.59.0
  questions:
  - variable: PROMETHEUS_CONFIG
    description: "Prometheus config"
    label: "Prometheus config"
    type: "multiline"
    required: true
    default: |
      global:
        scrape_interval:     15s
        evaluation_interval: 15s
        external_labels:
            monitor: 'exporter-metrics'

      scrape_configs:
      - job_name: 'HostsMetrics'
        dns_sd_configs:
        - names:
          - node-exporter
          refresh_interval: 15s
          type: A
          port: 9100

      - job_name: 'ContainerMetrics'
        dns_sd_configs:
        - names:
          - ranch-eye
          refresh_interval: 15s
          type: A
          port: 9104

      - job_name: 'rancher-api'
        static_configs:
          - targets:
            - 'prometheus-rancher-exporter:9010'

      - job_name: 'Prometheus'
        static_configs:
          - targets:
            - '127.0.0.1:9090'

prometheus:
  scale: 1
  metadata:
    prometheus-config: |
      ${PROMETHEUS_CONFIG}
  health_check:
    port: 9090
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000

alertmanager:
  scale: 1

influxdb:
  scale: 1
  health_check:
    port: 8086
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000

grafana:
  scale: 1
  health_check:
    port: 3000
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000

prometheus-rancher-exporter:
  scale: 1
  upgrade_strategy:
    start_first: true
  health_check:
    port: 9010
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000