keycloak:
  environment:
    KEYCLOAK_USER: ${KEYCLOAK_USER}
    KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
  labels:
    io.rancher.container.pull_image: always
    io.rancher.sidekicks: keycloak-datavolume
  tty: true
  image: jboss/keycloak
  stdin_open: true
  volumes_from:
  - keycloak-datavolume
keycloak-datavolume:
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
  - /opt/jboss/keycloak
  entrypoint: /bin/true
  image: jboss/keycloak

