keycloak-proxy:
  image: adopteunops/keycloak-http-proxy:3.2.1
  labels:
    io.rancher.sidekicks: keycloak-proxy-config
  tty: true
  stdin_open: true
  volumes_from:
  - keycloak-proxy-config
keycloak-proxy-config:
  image: adopteunops/keycloak-http-proxy-config:1.0.0
