curator:
  external_links:
  - ${elasticsearch_link}:elasticsearch
  environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_USERNAME: ${elasticsearch_username}
      ELASTICSEARCH_PASSWORD: ${elasticsearch_password}
      CRON_EXPR: ${cron_expr}
  image: adopteunops/elasticsearch-curator:1.0.0
  tty: true
  stdin_open: true
