.catalog:
  name: "curator"
  version: "5.2.0"
  description: "Provide a elasticsearch-curator stack"
  questions:
      - variable: "curator_actions"
        description: "Curator actions config"
        label: "Curator Actions"
        type: "multiline"
        required: true
        default: |
          actions:
            1:
              action: delete_indices
              description: >-
                Delete indices older than 45 days (based on index name), for logstash-
                prefixed indices. Ignore the error if the filter does not result in an
                actionable list of indices (ignore_empty_list) and exit cleanly.
              options:
                ignore_empty_list: True
              filters:
              - filtertype: pattern
                kind: prefix
                value: logstash-
              - filtertype: age
                source: name
                direction: older
                timestring: '%Y.%m.%d'
                unit: days
                unit_count: 45
            2:
              action: forcemerge
              description: >-
                forceMerge logstash- prefixed indices older than 2 days (based on index
                creation_date) to 2 segments per shard.  Delay 120 seconds between each
                forceMerge operation to allow the cluster to quiesce. Skip indices that
                have already been forcemerged to the minimum number of segments to avoid
                reprocessing.
              options:
                max_num_segments: 2
                delay: 120
                timeout_override:
                ignore_empty_list: True
                continue_if_exception: False
              filters:
              - filtertype: pattern
                kind: prefix
                value: logstash-
                exclude:
              - filtertype: age
                source: creation_date
                direction: older
                unit: days
                unit_count: 2
                exclude:
              - filtertype: forcemerged
                max_num_segments: 2
                exclude:
      - variable: "cron_expr"
        description: Cron based expression to trigger curator
        label: "Cron based expression"
        default: "0 22 * * *"
        required: true
        type: "string"
      - variable: "elasticsearch_link"
        description: |
          stack/service link or external service link to elasticsearch
          cluster.
        label: "Elasticsearch stack/service"
        default: "es/elasticsearch-clients"
        required: true
        type: "service"
      - variable: "elasticsearch_username"
        description: Elasticsearch username, leave it blank if no auth mechanism
        label: "Elasticsearch Username"
        default: ""
        type: "string"
      - variable: "elasticsearch_password"
        description: Elasticsearch password, leave it blank if no auth mechanism
        label: "Elasticsearch Password"
        default: ""
        type: "string"
curator:
  metadata:
    curator-actions: |
      ${curator_actions}
