registry:
  ports:
  - 5000:5000/tcp
  environment:
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
    REGISTRY_HTTP_TLS_KEY: /certs/domain.key
  labels:
    io.rancher.sidekicks: create-certs,registry-auth,registry-datavolume
    io.rancher.container.pull_image: always
  tty: true
  image: registry:2
  volumes_from:
  - create-certs
  - registry-auth
  - registry-datavolume
  stdin_open: true
registry-datavolume:
  labels:
    io.rancher.container.start_once: 'true'
  tty: true
  image: busybox
  volumes:
  - /var/lib/docker/registry
  stdin_open: true
create-certs:
  environment:
    COMMON_NAME: ${FQDN}
    KEY_NAME: domain
  labels:
    io.rancher.container.start_once: 'true'
  tty: true
  image: centurylink/openssl
  volumes:
  - /certs
  stdin_open: true
registry-auth:
  labels:
    io.rancher.container.start_once: 'true'
  command:
  - htpasswd
  - -cBb
  - /auth/htpasswd
  - ${DOCKER_USERNAME}
  - ${DOCKER_PASSWORD}
  tty: true
  image: registry:2
  volumes:
  - /auth
  stdin_open: true
